-- EQUIPES D'UN CLUB
SELECT CLUB.NUMERO_CLUB, CLUB.NOM_CLUB, EQUIPE.NUMERO_EQUIPE FROM CLUB, EQUIPE, ENTRAINEUR, ANIMATION, ENTRAINE
       WHERE CLUB.NUMERO_CLUB = ANIMATION.NUMERO_CLUB
       AND ENTRAINEUR.NUMERO_ENTRAINEUR = ANIMATION.NUMERO_ENTRAINEUR
       AND ENTRAINE.NUMERO_EQUIPE = EQUIPE.NUMERO_EQUIPE
       AND ENTRAINE.NUMERO_ENTRAINEUR = ENTRAINEUR.NUMERO_ENTRAINEUR
ORDER BY CLUB.NUMERO_CLUB ASC	

--INFORMATIONS JOUEURS D'UN CLUB

--Requetes victoires equipes
select RTR_L.NUMERO_EQUIPE, ifnull(NB_VICTOIRE_DOMICILE,0)+ifnull(NB_VICTOIRE_EXTERIEUR,0) as NOMBRE_VICTOIRES
from (select NUMERO_EQUIPE, COUNT(RENCONTRE.NUMERO_RENCONTRE) AS NB_VICTOIRE_DOMICILE
    from EQUIPE
    left join RENCONTRE
    on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
    and SCORE_EQUIPE_DOMICILE > SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE) as RTR_L
left join (select NUMERO_EQUIPE_JOUE_EXTERIEUR AS NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_VICTOIRE_EXTERIEUR
    from RENCONTRE
    where SCORE_EQUIPE_DOMICILE < SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE_JOUE_EXTERIEUR) as RTR_R
on RTR_L.NUMERO_EQUIPE = RTR_R.NUMERO_EQUIPE;

-- Requete moyenne points par rencontre pour une date donnée
select SUM(POINTS_MARQUES_RENCONTRE)/
       (select COUNT(DATE_RENCONTRE) from RENCONTRE
                   where DATE_RENCONTRE = '2014-01-10')
as 'MOYENNE POINTS MARQUES', DATE_RENCONTRE from
   (select DATE_RENCONTRE, NUMERO_RENCONTRE, SCORE_EQUIPE_DOMICILE+SCORE_EQUIPE_EXTERIEUR AS POINTS_MARQUES_RENCONTRE from RENCONTRE) as TAB
group by DATE_RENCONTRE

--CLASSEMENT GENERAL methode “finale”, sans tables intermediaires (toutes les catégories apparaissent ->rajouter un where nom_categorie = ...)

select VIC.NUMERO_EQUIPE, NOMBRE_VICTOIRES, NOMBRE_NULS, NOMBRE_DEFAITES, PTS_VIC+PTS_NUL as POINTS, ifnull(DIFF_VICTOIRE,0)+ifnull(DIFF_DEFAITE,0) as GOALAVERAGE
from(select RTR_L.NUMERO_EQUIPE, ifnull(NB_VICTOIRE_DOMICILE,0)+ifnull(NB_VICTOIRE_EXTERIEUR,0) as NOMBRE_VICTOIRES, (ifnull(NB_VICTOIRE_DOMICILE,0)+ifnull(NB_VICTOIRE_EXTERIEUR,0))*3 as PTS_VIC,  ifnull(DIFF_VICTOIRE_DOMICILE,0)+ifnull(DIFF_VICTOIRE_EXTERIEUR,0) AS DIFF_VICTOIRE
        from(select NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_VICTOIRE_DOMICILE, SCORE_EQUIPE_DOMICILE-SCORE_EQUIPE_EXTERIEUR AS DIFF_VICTOIRE_DOMICILE
            from EQUIPE
            left join RENCONTRE
            on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
            and SCORE_EQUIPE_DOMICILE > SCORE_EQUIPE_EXTERIEUR
           group by NUMERO_EQUIPE) as RTR_L
    left join (
              select NUMERO_EQUIPE_JOUE_EXTERIEUR AS NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_VICTOIRE_EXTERIEUR, SCORE_EQUIPE_EXTERIEUR-SCORE_EQUIPE_DOMICILE AS DIFF_VICTOIRE_EXTERIEUR
          from RENCONTRE
        where SCORE_EQUIPE_DOMICILE < SCORE_EQUIPE_EXTERIEUR
            group by NUMERO_EQUIPE_JOUE_EXTERIEUR) as RTR_R
        on RTR_L.NUMERO_EQUIPE = RTR_R.NUMERO_EQUIPE
        group by NUMERO_EQUIPE) as VIC
,
    (select RTR_L.NUMERO_EQUIPE, ifnull(NB_NUL_DOMICILE,0)+ifnull(NB_NUL_EXTERIEUR,0) as NOMBRE_NULS,  ifnull(NB_NUL_DOMICILE,0)+ifnull(NB_NUL_EXTERIEUR,0) as PTS_NUL
     from (select NUMERO_EQUIPE, COUNT(RENCONTRE.NUMERO_RENCONTRE) AS NB_NUL_DOMICILE
     from EQUIPE
     left join RENCONTRE
     on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
     and SCORE_EQUIPE_DOMICILE = SCORE_EQUIPE_EXTERIEUR
     group by NUMERO_EQUIPE) as RTR_L
     left join (select NUMERO_EQUIPE_JOUE_EXTERIEUR AS NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_NUL_EXTERIEUR
    from RENCONTRE
    where SCORE_EQUIPE_DOMICILE = SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE_JOUE_EXTERIEUR) as RTR_R
on RTR_L.NUMERO_EQUIPE = RTR_R.NUMERO_EQUIPE
    group by NUMERO_EQUIPE) as NUL
,
     (select RTR_L.NUMERO_EQUIPE, ifnull(NB_DEFAITE_DOMICILE,0)+ifnull(NB_DEFAITE_EXTERIEUR,0) as NOMBRE_DEFAITES, ifnull(DIFF_DEFAITE_DOMICILE,0)+ifnull(DIFF_DEFAITE_EXTERIEUR,0) AS DIFF_DEFAITE
     from (select NUMERO_EQUIPE, COUNT(RENCONTRE.NUMERO_RENCONTRE) AS NB_DEFAITE_DOMICILE, SCORE_EQUIPE_DOMICILE-SCORE_EQUIPE_EXTERIEUR AS DIFF_DEFAITE_DOMICILE
     from EQUIPE
     left join RENCONTRE
     on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
     and SCORE_EQUIPE_DOMICILE < SCORE_EQUIPE_EXTERIEUR
     group by NUMERO_EQUIPE) as RTR_L
     left join (select NUMERO_EQUIPE_JOUE_EXTERIEUR AS NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_DEFAITE_EXTERIEUR, SCORE_EQUIPE_EXTERIEUR-SCORE_EQUIPE_DOMICILE AS DIFF_DEFAITE_EXTERIEUR
    from RENCONTRE
    where SCORE_EQUIPE_DOMICILE > SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE_JOUE_EXTERIEUR) as RTR_R
on RTR_L.NUMERO_EQUIPE = RTR_R.NUMERO_EQUIPE
    group by NUMERO_EQUIPE) as DEF

where DEF.NUMERO_EQUIPE = VIC.NUMERO_EQUIPE
and NUL.NUMERO_EQUIPE = VIC.NUMERO_EQUIPE
order by POINTS desc, GOALAVERAGE desc

--Meilleurs joueurs d'une journée (pour une catégorie)
select distinct NOM_JOUEUR, PRENOM_JOUEUR, PARTICIPATION.NUMERO_LICENCE, max(POINTS), FAUTES
       from PARTICIPATION, JOUEUR, RENCONTRE, EQUIPE
               where JOUEUR.NUMERO_LICENCE = PARTICIPATION.NUMERO_LICENCE
        and RENCONTRE.NUMERO_RENCONTRE = PARTICIPATION.NUMERO_RENCONTRE
        and (JOUEUR.NUMERO_EQUIPE = NUMERO_EQUIPE_JOUE_DOMICILE OR
            JOUEUR.NUMERO_EQUIPE = NUMERO_EQUIPE_JOUE_EXTERIEUR)
        and (EQUIPE.NUMERO_EQUIPE = NUMERO_EQUIPE_JOUE_DOMICILE OR
             EQUIPE.NUMERO_EQUIPE = NUMERO_EQUIPE_JOUE_EXTERIEUR)
        and EQUIPE.NOM_CATEGORIE = 'SENIOR'
        and NUMERO_JOURNEE = 1
order by POINTS desc, FAUTES asc

--Requetes victoire equipe avec contrainte de catégorie
select VIC1.NUMERO_EQUIPE, VIC1.NOMBRE_VICTOIRES, NOM_CATEGORIE
from(
select RTR_L.NUMERO_EQUIPE, ifnull(NB_VICTOIRE_DOMICILE,0)+ifnull(NB_VICTOIRE_EXTERIEUR,0) as NOMBRE_VICTOIRES
from (select NUMERO_EQUIPE, COUNT(RENCONTRE.NUMERO_RENCONTRE) AS NB_VICTOIRE_DOMICILE
    from EQUIPE
    left join RENCONTRE
    on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
    and SCORE_EQUIPE_DOMICILE > SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE) as RTR_L
left join (select NUMERO_EQUIPE_JOUE_EXTERIEUR AS NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_VICTOIRE_EXTERIEUR
    from RENCONTRE
    where SCORE_EQUIPE_DOMICILE < SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE_JOUE_EXTERIEUR) as RTR_R
on RTR_L.NUMERO_EQUIPE = RTR_R.NUMERO_EQUIPE)
as VIC1, EQUIPE
where EQUIPE.NOM_CATEGORIE = 'SENIOR'
and VIC1.NUMERO_EQUIPE = EQUIPE.NUMERO_EQUIPE
