---- CLUB ----
--------------

-- nom, localisation et numéro de club tous les clubs
SELECT *
FROM CLUB;
 
-- toutes les localisations des clubs
SELECT DISTINCT CLUB.LOCALISATION_CLUB
FROM CLUB;

-- toutes les noms des clubs
SELECT DISTINCT CLUB.NOM_CLUB
FROM CLUB;

---- RESPONSABLES ----
----------------------

-- président de chaque club
SELECT CLUB.NOM_CLUB, RESPONSABLE.NOM_RESPONSABLE, RESPONSABLE.PRENOM_RESPONSABLE
FROM CLUB, RESPONSABLE
WHERE CLUB.NUMERO_CLUB = RESPONSABLE.NUMERO_CLUB
AND RESPONSABLE.FONCTION = 'PRESIDENT';

-- responsables de chaque club
SELECT CLUB.NOM_CLUB, RESPONSABLE.NOM_RESPONSABLE, RESPONSABLE.PRENOM_RESPONSABLE, RESPONSABLE.FONCTION
FROM CLUB, RESPONSABLE
WHERE CLUB.NUMERO_CLUB = RESPONSABLE.NUMERO_CLUB

-- responsable d'un club donné
SELECT CLUB.NOM_CLUB, RESPONSABLE.NOM_RESPONSABLE, RESPONSABLE.PRENOM_RESPONSABLE, RESPONSABLE.FONCTION
FROM CLUB, RESPONSABLE
WHERE CLUB.NUMERO_CLUB = RESPONSABLE.NUMERO_CLUB
AND CLUB.NUMERO_CLUB = 1;

---- EQUIPES ----
-----------------

-- selectionne toutes les équipes d'une catégorie donnée
SELECT CLUB.NOM_CLUB, EQUIPE.NUMERO_EQUIPE, EQUIPE.NOM_CATEGORIE
FROM CLUB, ENTRAINEUR, ANIMATION, ENTRAINE, EQUIPE
WHERE CLUB.NUMERO_CLUB = ANIMATION.NUMERO_CLUB
AND ENTRAINEUR.NUMERO_ENTRAINEUR = ANIMATION.NUMERO_ENTRAINEUR 
AND ENTRAINE.NUMERO_EQUIPE = EQUIPE.NUMERO_EQUIPE
AND ENTRAINE.NUMERO_ENTRAINEUR = ENTRAINEUR.NUMERO_ENTRAINEUR
AND EQUIPE.NOM_CATEGORIE = 'SENIOR'; 

-- selectionne les équipes de chaque club
SELECT CLUB.NUMERO_CLUB, CLUB.NOM_CLUB, EQUIPE.NUMERO_EQUIPE FROM CLUB, EQUIPE, ENTRAINEUR, ANIMATION, ENTRAINE
       WHERE CLUB.NUMERO_CLUB = ANIMATION.NUMERO_CLUB
       AND ENTRAINEUR.NUMERO_ENTRAINEUR = ANIMATION.NUMERO_ENTRAINEUR
       AND ENTRAINE.NUMERO_EQUIPE = EQUIPE.NUMERO_EQUIPE
       AND ENTRAINE.NUMERO_ENTRAINEUR = ENTRAINEUR.NUMERO_ENTRAINEUR
ORDER BY CLUB.NUMERO_CLUB ASC


---- JOUEURS ----
-----------------

-- sélection de tous les joueurs de la fédération
SELECT JOUEUR.*, ENTREE.DATE_ENTREE_JOUEUR
FROM JOUEUR, ENTREE
WHERE JOUEUR.NUMERO_LICENCE = ENTREE.NUMERO_LICENCE

-- sélection de tous les joueurs pour une catégorie donnée
SELECT JOUEUR.*, EQUIPE.NUMERO_EQUIPE
FROM JOUEUR, EQUIPE
WHERE JOUEUR.NUMERO_EQUIPE = EQUIPE.NUMERO_EQUIPE
AND EQUIPE.NOM_CATEGORIE = 'SENIOR'
ORDER BY JOUEUR.NUMERO_LICENCE ASC;

--sélection de tous les joueurs dans un club donné
SELECT CLUB.NOM_CLUB, JOUEUR.*, ENTREE.DATE_ENTREE_JOUEUR
FROM CLUB, JOUEUR, ENTREE
WHERE CLUB.NUMERO_CLUB = ENTREE.NUMERO_CLUB
AND JOUEUR.NUMERO_LICENCE = ENTREE.NUMERO_LICENCE
ORDER BY JOUEUR.NUMERO_LICENCE ASC;



---- Statistiques ----
----------------------

--Requetes victoires equipes
select RTR_L.NUMERO_EQUIPE, ifnull(NB_VICTOIRE_DOMICILE,0)+ifnull(NB_VICTOIRE_EXTERIEUR,0) as NOMBRE_VICTOIRES
from (select NUMERO_EQUIPE, COUNT(RENCONTRE.NUMERO_RENCONTRE) AS NB_VICTOIRE_DOMICILE
    from EQUIPE
    left join RENCONTRE
    on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
    and SCORE_EQUIPE_DOMICILE > SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE) as RTR_L
left join (select NUMERO_EQUIPE_JOUE_EXTERIEUR AS NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_VICTOIRE_EXTERIEUR
    from RENCONTRE
    where SCORE_EQUIPE_DOMICILE < SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE_JOUE_EXTERIEUR) as RTR_R
on RTR_L.NUMERO_EQUIPE = RTR_R.NUMERO_EQUIPE;

-- Requete moyenne points par rencontre pour une date donnée
select SUM(POINTS_MARQUES_RENCONTRE)/
       (select COUNT(DATE_RENCONTRE) from RENCONTRE
                   where DATE_RENCONTRE = '2014-01-10')
as 'MOYENNE POINTS MARQUES', DATE_RENCONTRE from
   (select DATE_RENCONTRE, NUMERO_RENCONTRE, SCORE_EQUIPE_DOMICILE+SCORE_EQUIPE_EXTERIEUR AS POINTS_MARQUES_RENCONTRE from RENCONTRE) as TAB
group by DATE_RENCONTRE

--CLASSEMENT GENERAL methode “finale”, sans tables intermediaires (toutes les catégories apparaissent ->rajouter un where nom_categorie = ...)

select VIC.NUMERO_EQUIPE, NOMBRE_VICTOIRES, NOMBRE_NULS, NOMBRE_DEFAITES, PTS_VIC+PTS_NUL as POINTS, ifnull(DIFF_VICTOIRE,0)+ifnull(DIFF_DEFAITE,0) as GOALAVERAGE
from(select RTR_L.NUMERO_EQUIPE, ifnull(NB_VICTOIRE_DOMICILE,0)+ifnull(NB_VICTOIRE_EXTERIEUR,0) as NOMBRE_VICTOIRES, (ifnull(NB_VICTOIRE_DOMICILE,0)+ifnull(NB_VICTOIRE_EXTERIEUR,0))*3 as PTS_VIC,  ifnull(DIFF_VICTOIRE_DOMICILE,0)+ifnull(DIFF_VICTOIRE_EXTERIEUR,0) AS DIFF_VICTOIRE
        from(select NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_VICTOIRE_DOMICILE, SCORE_EQUIPE_DOMICILE-SCORE_EQUIPE_EXTERIEUR AS DIFF_VICTOIRE_DOMICILE
            from EQUIPE
            left join RENCONTRE
            on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
            and SCORE_EQUIPE_DOMICILE > SCORE_EQUIPE_EXTERIEUR
           group by NUMERO_EQUIPE) as RTR_L
    left join (
              select NUMERO_EQUIPE_JOUE_EXTERIEUR AS NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_VICTOIRE_EXTERIEUR, SCORE_EQUIPE_EXTERIEUR-SCORE_EQUIPE_DOMICILE AS DIFF_VICTOIRE_EXTERIEUR
          from RENCONTRE
        where SCORE_EQUIPE_DOMICILE < SCORE_EQUIPE_EXTERIEUR
            group by NUMERO_EQUIPE_JOUE_EXTERIEUR) as RTR_R
        on RTR_L.NUMERO_EQUIPE = RTR_R.NUMERO_EQUIPE
        group by NUMERO_EQUIPE) as VIC
,
    (select RTR_L.NUMERO_EQUIPE, ifnull(NB_NUL_DOMICILE,0)+ifnull(NB_NUL_EXTERIEUR,0) as NOMBRE_NULS,  ifnull(NB_NUL_DOMICILE,0)+ifnull(NB_NUL_EXTERIEUR,0) as PTS_NUL
     from (select NUMERO_EQUIPE, COUNT(RENCONTRE.NUMERO_RENCONTRE) AS NB_NUL_DOMICILE
     from EQUIPE
     left join RENCONTRE
     on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
     and SCORE_EQUIPE_DOMICILE = SCORE_EQUIPE_EXTERIEUR
     group by NUMERO_EQUIPE) as RTR_L
     left join (select NUMERO_EQUIPE_JOUE_EXTERIEUR AS NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_NUL_EXTERIEUR
    from RENCONTRE
    where SCORE_EQUIPE_DOMICILE = SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE_JOUE_EXTERIEUR) as RTR_R
on RTR_L.NUMERO_EQUIPE = RTR_R.NUMERO_EQUIPE
    group by NUMERO_EQUIPE) as NUL
,
     (select RTR_L.NUMERO_EQUIPE, ifnull(NB_DEFAITE_DOMICILE,0)+ifnull(NB_DEFAITE_EXTERIEUR,0) as NOMBRE_DEFAITES, ifnull(DIFF_DEFAITE_DOMICILE,0)+ifnull(DIFF_DEFAITE_EXTERIEUR,0) AS DIFF_DEFAITE
     from (select NUMERO_EQUIPE, COUNT(RENCONTRE.NUMERO_RENCONTRE) AS NB_DEFAITE_DOMICILE, SCORE_EQUIPE_DOMICILE-SCORE_EQUIPE_EXTERIEUR AS DIFF_DEFAITE_DOMICILE
     from EQUIPE
     left join RENCONTRE
     on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
     and SCORE_EQUIPE_DOMICILE < SCORE_EQUIPE_EXTERIEUR
     group by NUMERO_EQUIPE) as RTR_L
     left join (select NUMERO_EQUIPE_JOUE_EXTERIEUR AS NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_DEFAITE_EXTERIEUR, SCORE_EQUIPE_EXTERIEUR-SCORE_EQUIPE_DOMICILE AS DIFF_DEFAITE_EXTERIEUR
    from RENCONTRE
    where SCORE_EQUIPE_DOMICILE > SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE_JOUE_EXTERIEUR) as RTR_R
on RTR_L.NUMERO_EQUIPE = RTR_R.NUMERO_EQUIPE
    group by NUMERO_EQUIPE) as DEF

where DEF.NUMERO_EQUIPE = VIC.NUMERO_EQUIPE
and NUL.NUMERO_EQUIPE = VIC.NUMERO_EQUIPE
and EQUIPE.NUMERO_EQUIPE = VIC.NUMERO_EQUIPE
and EQUIPE.NOM_CATEGORIE = 'SENIOR'
order by POINTS desc, GOALAVERAGE desc

--Meilleurs joueurs d'une journée (pour une catégorie)
select distinct NOM_JOUEUR, PRENOM_JOUEUR, PARTICIPATION.NUMERO_LICENCE, max(POINTS), FAUTES
       from PARTICIPATION, JOUEUR, RENCONTRE, EQUIPE
               where JOUEUR.NUMERO_LICENCE = PARTICIPATION.NUMERO_LICENCE
        and RENCONTRE.NUMERO_RENCONTRE = PARTICIPATION.NUMERO_RENCONTRE
        and (JOUEUR.NUMERO_EQUIPE = NUMERO_EQUIPE_JOUE_DOMICILE OR
            JOUEUR.NUMERO_EQUIPE = NUMERO_EQUIPE_JOUE_EXTERIEUR)
        and (EQUIPE.NUMERO_EQUIPE = NUMERO_EQUIPE_JOUE_DOMICILE OR
             EQUIPE.NUMERO_EQUIPE = NUMERO_EQUIPE_JOUE_EXTERIEUR)
        and EQUIPE.NOM_CATEGORIE = 'SENIOR'
        and NUMERO_JOURNEE = 1
order by POINTS desc, FAUTES asc

--Requetes victoire equipe avec contrainte de catégorie
select VIC1.NUMERO_EQUIPE, VIC1.NOMBRE_VICTOIRES, NOM_CATEGORIE
from(
select RTR_L.NUMERO_EQUIPE, ifnull(NB_VICTOIRE_DOMICILE,0)+ifnull(NB_VICTOIRE_EXTERIEUR,0) as NOMBRE_VICTOIRES
from (select NUMERO_EQUIPE, COUNT(RENCONTRE.NUMERO_RENCONTRE) AS NB_VICTOIRE_DOMICILE
    from EQUIPE
    left join RENCONTRE
    on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
    and SCORE_EQUIPE_DOMICILE > SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE) as RTR_L
left join (select NUMERO_EQUIPE_JOUE_EXTERIEUR AS NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_VICTOIRE_EXTERIEUR
    from RENCONTRE
    where SCORE_EQUIPE_DOMICILE < SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE_JOUE_EXTERIEUR) as RTR_R
on RTR_L.NUMERO_EQUIPE = RTR_R.NUMERO_EQUIPE)
as VIC1, EQUIPE
where EQUIPE.NOM_CATEGORIE = 'SENIOR'
and VIC1.NUMERO_EQUIPE = EQUIPE.NUMERO_EQUIPE
